# Generated by Django 5.0.3 on 2024-05-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('userpswd', models.CharField(max_length=200)),
                ('userlat', models.IntegerField()),
                ('userlong', models.IntegerField()),
            ],
        ),
    ]
