services:
  likemeappl:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      # - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    depends_on:
      - postgres
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  postgres:
    container_name: postgres
    restart: always
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    # healthcheck:
    #   test: [ "CMD", "pg_isready" ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  nginx:
    build:
      context: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - likemeappl

volumes:
  postgres_volume:
  static_volume:
  media_volume:
