
services:
  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

  likemeappl:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app:rw
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    depends_on:
      - postgres

  nginx:
    build:
      context: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - likemeappl

volumes:
  postgres_volume:
  static_volume:
  media_volume:
